Replacing Result enum in favor of the one available in Swift 5
FortechRomania/ios-mvp-clean-architecture pull request #15
Opened 2019-10-23 17:59 UTC by AnasAlhasani

2020-01-27 07:06 UTC, cosminstirbu requested changes
Hi - thank you for your PR.

I've left a few comments, please have a look over them.

2020-01-27 07:06 UTC, cosminstirbu commented on LibraryTests/Result.swift
>  import Foundation
II think we can remove this file altogether.

2020-01-27 07:06 UTC, cosminstirbu commented on LibraryTests/Gateways/CacheBooksGatewayTest.swift
> +                      XCTAssertTrue(expectedResultToBeReturned == result, "The expected result wasn't returned")
Normally I would avoid XCTAssertTrue just because the failure message is not as meaningful as an XCTAssertEqual would be.

However, for the purpose of this sample, I think it's fine :-?

2020-01-27 07:06 UTC, cosminstirbu commented on LibraryTests/Result.swift
>  import Foundation
Or maybe not, as we're using == in XCTAssertTrue. However, since we're relying on a custom == operator, we might as well keep using XCTAssertEqual :-?

2020-01-27 21:38 UTC, AnasAlhasani commented on LibraryTests/Result.swift
>  import Foundation
The problem is that the type of `success` (Void)/`failure` we're using not conform to `Equatable`, that's why I took the advantage of the custom operator and used `XCTAssertTrue` instead.

2020-01-27 21:41 UTC, AnasAlhasani commented on LibraryTests/Gateways/CacheBooksGatewayTest.swift
> +                      XCTAssertTrue(expectedResultToBeReturned == result, "The expected result wasn't returned")
I totally agree with you. but I think it's just fine.

2020-01-28 12:47 UTC, cosminstirbu approved these changes

2020-01-28 12:48 UTC, merged